### PR TITLE
Nc/75 acl ui

### LINKED ISSUE #74: Set default ACL when creating node from inside dataviewer

### LINKED ISSUE #75: UI Improvement for showing ACL for each node
- [x] Ensure each node has own default ACL when created from the dataviewer

- [x] When no node is selected, remove ACL div

- [x] Disable Delete and Edit buttons when no nodes are available

### LINKED ISSUE #79: Add Node not working second time
Server Version: 1.2.0
Client Version: N/A

Steps to Reproduce:
*  On an empty instance of CSync, add a node from the dataviewer
*  Delete this node
*  Try to add another node

Expected Behavior: should add a new node
Actual Behavior: does nothing

### PR DESCRIPTION
**Pull request by narinearraul**
Resolves #75
Resolves #74 
Resolves #79 

Proposed Changes:
*  Edit and Delete buttons hidden when no data is selected
*  Nodes created from dataviewer have default ACL now
*  ACL div cleared when no info
* Clearing selectedNode in the tree when nothing is selected + error handling of when selectedNode is null

DCO1.1 Signed-off-by: Narine Cholakyan <narinearraul@gmail.com>

### CODE REVIEW

**Comment by boopt2** [comment]
Hi narinearraul,

Thanks for submitting this pull request!

I can confirm that the DCO1.1 sign-off has been included. It is okay to process this pull request.

dco-bot

**Comment by krbrewer** [comment]
When I add a node to a csync that is empty and then delete that node, I am unable to add any more new nodes. After deleting the first node the add button turns grey and won't allow adding more nodes until refreshing the page.

**Comment by narinearraul** [comment]
@krbrewer https://github.com/csync/csync-server/issues/79

**Comment by boopt2** [comment]
I found a bug.

Make node a.
make node a.b
Make node a.b.c
Write "test" to a.b.c.
Hit refresh
Expected Behavior: See "test" when a.b.c loads
Actual Behavior: See nothing until a.b.c is reselected

**Comment by narinearraul** [comment]
@krbrewer  https://github.com/csync/csync-server/issues/82

**Comment by narinearraul** [comment]
@boopt2 I've addressed #79 here also. Could you test and merge if all good?

**Pull request merged**
